### ISSUE TITLE
Exception / failure when number of unique loci exceeds 1000

### ISSUE THREAD

**Issue by Skybeetle** [perslab/depict#3]
Dear Tune H Pers,
When our number of unique loci exceeds 1000, we are getting an exception and analysis failure.
Could you please correct the following lines (currently 702 and 703) in the code file PerformPathwayAnalysisSusceptibilityLoci.java
From:
 nrGenesPerUniqueLociEmpiricPerms = new int[nrPerms + nrReps][1000];
 geneStartIndexPermutedLociEmpiricPerms = new int[nrPerms + nrReps][1000];
To:
 nrGenesPerUniqueLociEmpiricPerms = new int[nrPerms + nrReps][nrUniqueLoci];
 geneStartIndexPermutedLociEmpiricPerms = new int[nrPerms + nrReps][nrUniqueLoci];

This correction and rebuild eliminated the problem for us. We exceed 1500 unique loci. No hurry, we are fine now, but maybe for one of the future builds?

**Comment by tunepers** [comment]
Thank you for making us aware of this error.  It has now been resolved.

**Comment by ZKamali** [comment]
Dear Tune H Pers,
The error prevails even after correction of this section in the current version. In addition, number of precomputed loci (permutation files) are usually less than what is specified in configuration file (.cfg). for example when we specify 500 it generates 495. Interestingly in all cases these missing files are the same! (i.e "permutation57.txt.gz", "permutation69.txt.gz", "permutation71.txt.gz", "permutation171.txt.gz" and "permutation182.txt.gz"). Please let us know how to fix these problems.
